version: '3'

volumes:
  static:

services:
  server:
    image: sensor-data-server
    volumes:
      - /app/static
    ports:
      - "6000:6000"
    networks:
      - default

  sender:
    image: data-source
    depends_on:
      - server
    networks:
      - default

networks:
  default: